---
- name: Pull and Run Docker Image
  hosts: localhost
  remote_user: ansible
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "r3dacted42/scicalc"
        source: pull
      register: docker_pull_result
    
    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
    
    - name: Start Docker Service
      service:
        name: docker
        state: started
    
    - name: Remove Existing Container if it Exists
      shell: docker stop scicalc || true && docker rm scicalc || true
    
    - name: Run Container
      shell: docker run -it -p5000:5000 -d --name scicalc r3dacted42/scicalc
    
    - name: Print Completion Message
      debug:
        msg: Application running at "http://localhost:5000"